#!/bin/bash

echo "$1"

if [ "$1" == "-c" ]; then
	WALL=$(nsxiv -to ~/Desktop/arnaud/wallpaper)
	if [ -n "$WALL" ]; then
		wal -i $WALL && touch ~/Desktop/arnaud/code/eww/eww-bar/eww/mybar/eww.scss;
		$HOME/Desktop/arnaud/code/bash/update-rofi &
		$HOME/Desktop/arnaud/code/bash/update-eww &
	fi
else
	wal -i ~/Desktop/arnaud/wallpaper && touch ~/Desktop/arnaud/code/eww/eww-bar/eww/mybar/eww.scss;
	$HOME/Desktop/arnaud/code/bash/update-rofi &
	$HOME/Desktop/arnaud/code/bash/update-eww &
fi
