#!/bin/bash

echo "$1"

if [ "$1" == "-c" ]; then
	WALL=$(nsxiv -to $HOME/wallpapers)
	if [ -n "$WALL" ]; then
		wal -i $WALL &
		$HOME/Desktop/arnaud/code/bash/update-rofi &
		$HOME/Desktop/arnaud/code/bash/update-eww &
	fi
else
	wal -i $HOME/Desktop/wallpapers &
	$HOME/Desktop/arnaud/code/bash/update-rofi &
	$HOME/Desktop/arnaud/code/bash/update-eww &
fi
