#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

## sources pywal colors
source ~/.cache/wal/colors.sh

# MONITORS
#xrandr --output HDMI-1 --mode 1920x1080 --rate 144 --right-of eDP-1

# virtual desktops
bspc monitor eDP-1 -d 1 2 3 4 &
#bspc monitor HDMI-1 -d I II III IV

# border color, gaps...
bspc config border_width	6
bspc config window_gap        	45

## using pywal colors
bspc config focused_border_color "$color1"
bspc config active_border_color "$color0"
bspc config normal_border_color "$color0"

bspc config split_ratio          0.50
bspc config borderless_monocle   true 
bspc config gapless_monocle      true


# A few rules, not necessary because I don't use it anymore
#bscp rule -a "plank" layer=above
#bscp rule -a "cairo-dock" layer=above
#bscp rule -a "cairo-dock-sub" layer=above


# Starting some programs, such as the bar...

dunst &
eww open -c $HOME/.config/eww/eww-bar bar_left
eww open -c $HOME/.config/eww/eww-bar bar_center
eww open -c $HOME/.config/eww/eww-bar bar_right
picom --config $HOME/.config/bspwm/picom-config.conf -b &

# starting spotlight to gets started doing stuff !

bash -c /home/arnaud/.config/rofi/launchers/colorful/spotlight &
