#!/bin/bash

# Source pywal colors
source "${HOME}/.cache/wal/colors.sh"

# Output path for your rofi theme
ROFI_THEME="${HOME}/.config/rofi/my-rofi/colors.rasi"

cat > "$ROFI_THEME" <<EOF
/* pywal theme - auto generated */
* {
  al:  ${color0};
  bg:  ${background};
  se:  ${color2};
  fg:  ${foreground};
  ac:  ${color1};
}
EOF
